import type { Metadata } from "next";
import "./globals.css";
import NavbarInsta from "./_components/navbar";
import FooterInsta from "./_components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col">
        {children}
        <FooterInsta />
      </body>
    </html>
  );
}
