import type { Metadata } from "next";
import "./globals.css";
import FooterInsta from "./_components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-zinc-950">
        <div className="flex">
          {/* Desktop Sidebar */}
          <div className="hidden md:flex">
            <FooterInsta />
          </div>

          {/* Main Content */}
          <main className="flex justify-center w-full bg-black min-h-screen md:ml-20">
            <div className="w-full max-w-md pb-20">{children}</div>
          </main>

          {/* Mobile Footer */}
          <div className="md:hidden">
            <FooterInsta />
          </div>
        </div>
      </body>
    </html>
  );
}
