import type { Metadata } from "next";
import "./globals.css";
import FooterInsta from "./_components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-full flex flex-col bg-zinc-950">
        <div className="w-full max-w-md mx-auto bg-black min-h-screen md:max-w-none md:mx-0">
          {children}
          <FooterInsta />
        </div>
      </body>
    </html>
  );
}
